name: Application Deploy
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint Check
        run: npm run lint
      - name: Run Tests
        run: npm run test
      - name: Build App
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."