name: Output Event Details
on: workflow_dispatch
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context event details
      run: echo "${{ toJSON(github.issues) }}"