name: Application Deploy Multijob
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint Check
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."